#!/bin/sh

set -e

BASE=/tmp/mosbench

if [ $# != 1 ]; then
    cat >&2 <<EOF
Usage: $0 fstype

Remove files in the MOSBENCH mount for the given file system type (as
created by mkmounts).
EOF
    exit 2
fi

case $1 in
    tmpfs|tmpfs-separate)
        rm -rf $BASE/$1/[0-9]*/*
        if [ -e $BASE/$1/spool/log ]; then
            rm -rf $BASE/$1/spool/log/*
        fi
        ;;
    hugetlb)
        for f in $BASE/$1/pagefile*; do
            # hugetlbfs WON'T FREE the huge pages backing these files
            # if we simply delete them.  We have to first truncate
            # them, which will free the pages.
            truncate --size=0 $f
            rm $f
        done
        ;;
    *)
        echo "Unknown file system type $1" &>2
        exit 1
        ;;
esac
