#!/usr/bin/python

import sys, os, time

SC_CLK_TCK = float(os.sysconf("SC_CLK_TCK"))
cols = ["user", "nice", "sys", "idle",
        "iowait", "irq", "softirq",
        "steal", "guest"]

f = file("/proc/stat", "r", 0)

def sample():
    f.seek(0)
    for l in f:
        if not l.startswith("cpu "):
            continue
        return [int(p)/SC_CLK_TCK for p in l[4:].strip().split()]
    raise RuntimeError("Failed to find CPU statistics")

def diff(a, b):
    return [a1 - b1 for a1, b1 in zip(a, b)]

start, sreal = sample(), time.time()
try:
    while True:
        time.sleep(1<<31)
except KeyboardInterrupt:
    end, ereal = sample(), time.time()
    print "real %g" % (ereal - sreal)
    delta = diff(end, start)
    if len(delta) < len(cols):
        delta.extend([0] * (len(cols) - len(delta)))
    for v, l in zip(delta, cols):
        print "%s %g" % (l, v)
